### ISSUE TITLE
sweep: Please write unit tests for all files

### ISSUE THREAD

**Issue by reconsumeralization** [reconsumeralization/tk#1]
please write unit tests for all files one by one.

<details open>
<summary>Checklist</summary>

- [X] Modify `test_backend.py` ✓ https://github.com/reconsumeralization/tk/commit/ddab6311137a45f3e78b6e59d964901a0224aac4 [Edit](https://github.com/reconsumeralization/tk/edit/sweep/add-unit-tests/test_backend.py)
- [X] Modify `test_frontend.ts` ✓ https://github.com/reconsumeralization/tk/commit/248e66c5c31e42c302f08106d1ded3d5aadcd8e5 [Edit](https://github.com/reconsumeralization/tk/edit/sweep/add-unit-tests/test_frontend.ts)

![Flowchart](https://raw.githubusercontent.com/reconsumeralization/tk/sweep/assets/b253c031551b3362eac28bc04fc80d064aaffa58bd34e2e34ff8fa79ab8bbfda_1_flowchart.svg)
</details>

**Comment by wwzeng1** [comment]
Hi @reconsumeralization! I reran this PR :)
